### ISSUE TITLE
EXPOSE 3000 is missing

### ISSUE THREAD

**Issue by p4block** [linuxserver/docker-clarkson#14]
EXPOSE should be used to tell Docker that this container listens on port 3000. Without it, you need a "useless" port map to the host when running a reverse proxy.

**Comment by Roxedus** [comment]
You can set expose in your compose/run, without mapping a port, for discoverability.

**Comment by p4block** [comment]
It still should be set in the compose per the docker spec, the application is not containerized properly if it isn't. Setting it "as is" on the compose is not the same thing and will often cause it to get mapped to a random available port under certain environments.

**Comment by aptalca** [comment]
`EXPOSE` in dockerfile is purely for informational purposes. It has no actual function.

**Comment by p4block** [comment]
Without it, Traefik doesn't pick up the container as it doesn't get the very important information that there's a service listening there, so it's very much functional. Additionally, the user is supposed to see the service is supposed to listen on whatever port(s) in `docker ps`, for example. 

This is the only container I run that for no reason whatsoever doesn't provide this very informational information

**Comment by aptalca** [comment]
It's traefik functionality to pick up info from a container and act on it. It is not a docker function. Add a label or whatever traefik needs to tell it what port it's listening on.

**Comment by p4block** [comment]
The container is supposed to provide that information, that's why EXPOSE exists and why all appropriately done container images do it. 

For some reason you seem to be very against adding a single line to the Dockerfile that is supposed to be there anyway.

**Comment by p4block** [comment]
![image](https://user-images.githubusercontent.com/5960575/106373296-59474380-6378-11eb-92e9-1dd67d248f11.png)

The ports column is there for a reason.

**Comment by aptalca** [comment]
Yes, I'm against it. I'm for removing them from all of our images. What ports you want to map or how you want to make the services accessible is a decision the end user (server admin) needs to make during runtime, not the dev providing the image during build time. Our documentation covers all that already. No need to add extra layers to the image.

Plus, some images expose a bunch of ports like [unifi](https://github.com/linuxserver/docker-unifi-controller/blob/master/Dockerfile#L49), but only one of those is the webgui. Not very useful for traefik, is it?

**Comment by p4block** [comment]
Well, remove them all or add it to this one, the current state is inconsistent ¯\\\_(ツ)_/¯

As you said yourself, the expose is a hint. It helps the user know which ports the container listens for stuff better than any documentation you may write as it is _just_ there. It's not limiting in any way and just adds value (and you are not ignoring a Docker feature) 

When there is more than 1 exposed port Traefik won't do anything without specifying the port. Thankfully, that is the minority of images in my case, but at least I can check from which one I'm supposed to be picking. 

It's been a while since I built images in any meaningful way but iirc, where the EXPOSE is placed may help with caching.
